### ISSUE TITLE
#运行时发生了一些错误...

### ISSUE THREAD

**Issue by Newisland2** [guoguoly/Auto_booking#3]
学长好，我想问运行时一直提示验证码识别有问题，感觉是PIL的原因，网上也没找着
`成功登录
预约ing
Traceback (most recent call last):

  File "<ipython-input-24-6c334a4a08f8>", line 58, in <module>
    yuyue_flag = yuyue(session,j[0],str(i),changguanID,ids,phoneNum)

  File "<ipython-input-23-71b01119fdb4>", line 91, in yuyue
    validcode = recognize_captcha(tempIm)#验证码识别

  File "<ipython-input-23-71b01119fdb4>", line 72, in recognize_captcha
    im = Image.open(img_path)

  File "C:\Users\New_island\AppData\Roaming\Python\Python37\site-packages\PIL\Image.py", line 3009, in open
    "cannot identify image file %r" % (filename if filename else fp)

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000016F4357ACA8>`
可以请学长帮忙看一看吗？感谢！

**Comment by guoguoly** [comment]
检查过了，简单的说就是，预约中验证码的申请地址发生了改变，
从
`http://yuyue.seu.edu.cn:80/eduplus/control/validateimage`
变为了
`http://yuyue.seu.edu.cn/eduplus/validateimage`
而且，验证码也添加了一些噪声，直接使用tesseract已经无法解决了，可以直接使用ddddocr解决。

**Comment by guoguoly** [comment]
估计是发现有人滥用了，我这里不再修改了。
